// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEmS3bJHX8F1Wbix5xurSfsbcwRM5BklM',
    appId: '1:1075031266297:web:a3032a51732fe76888a328',
    messagingSenderId: '1075031266297',
    projectId: 'movies-39976',
    authDomain: 'movies-39976.firebaseapp.com',
    databaseURL: 'https://movies-39976-default-rtdb.firebaseio.com',
    storageBucket: 'movies-39976.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTu83fdSuYdRy2LwqxO6iqx68CcposnVo',
    appId: '1:1075031266297:android:796efa42341116f788a328',
    messagingSenderId: '1075031266297',
    projectId: 'movies-39976',
    databaseURL: 'https://movies-39976-default-rtdb.firebaseio.com',
    storageBucket: 'movies-39976.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ3gqsMdjzzcJghsSWO0Xgy5ylanr1_BM',
    appId: '1:1075031266297:ios:a7c989dac486be4b88a328',
    messagingSenderId: '1075031266297',
    projectId: 'movies-39976',
    databaseURL: 'https://movies-39976-default-rtdb.firebaseio.com',
    storageBucket: 'movies-39976.appspot.com',
    iosClientId: '1075031266297-odnphioncuf529uv40ekc5ijbf2fcihd.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ3gqsMdjzzcJghsSWO0Xgy5ylanr1_BM',
    appId: '1:1075031266297:ios:58429a2dc9aa263288a328',
    messagingSenderId: '1075031266297',
    projectId: 'movies-39976',
    databaseURL: 'https://movies-39976-default-rtdb.firebaseio.com',
    storageBucket: 'movies-39976.appspot.com',
    iosClientId: '1075031266297-b5je4ns5ttvdviav6crnfopnnln90k6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflix.RunnerTests',
  );
}
